### ISSUE TITLE
[Feature] Allow customizing API URL

### ISSUE THREAD

**Issue by Nicd** [maxdeviant/code-stats-ls#1]
I use a custom API URL to pass my API calls through a local Python script that sends them to both the website and my local installation of it, for testing. Also some people might set up their own instance, in which case it's useful to be able to change the URL.

**Comment by maxdeviant** [comment]
This is available in v0.2.0 of the language server.

You can set the `CODE_STATS_API_URL` environment variable to override the API URL from `https://codestats.net`.

I may also look into making this configurable for the Zed extension via a setting.
